version: '3.8'

services:
  postgres:
    platform: linux/amd64
    image: "postgres:15.4"
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=ride_engine
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - "./docker_volume/postgres:/var/lib/postgresql/data"
#      - "./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql"
    container_name: ride_engine-postgres
    networks:
      - ride_engine_network

  mongodb:
    image: mongo:latest
    ports:
      - "27016:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=ride_engine
    volumes:
      - "./storage/mongodb:/data/db"
#      - "./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init.js:ro"
    container_name: ride_engine-mongo
    networks:
      - ride_engine_network

  redis:
    image: redis:7-alpine
    container_name: ride_engine-redis
    ports:
      - "6389:6379"
    volumes:
      - "./storage/redis:/data"
    networks:
      - ride_engine_network
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: ride_engine-app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ride_engine
      - MONGODB_URI=mongodb://root:secret@mongodb:27017
      - MONGODB_DATABASE=ride_engine
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8080
      - JWT_SECRET=your-secret-key-change-this-in-production
      - JWT_EXPIRATION=24h
    depends_on:
      - postgres
      - mongodb
      - redis
    restart: always
    networks:
      - ride_engine_network



volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  ride_engine_network:
    driver: bridge
